@extends('front.layouts.app')
@inject('safeHtml','App\Services\Frontend\SafeHtml')
@inject('embeds','App\Services\Frontend\VideoEmbedService')
@section('content')
@include('front.sections.hero')
@include('front.sections.trainings')
@include('front.sections.about')
@include('front.sections.capacity-report')
@if($latestResources->isNotEmpty())
    @include('front.sections.resources')
@endif
@if($team->isNotEmpty())
    @include('front.sections.team')
@endif
@include('front.sections.halls')
@if($videos->contains(fn ($video) => $embeds->url($video->video_url)))
    @include('front.sections.videos')
@endif
@if($latestNews->isNotEmpty())
    @include('front.sections.news')
@endif
@endsection
